### ISSUE TITLE
No JS File

### ISSUE THREAD

**Issue by LogicalSoIutions** [jctrvlr/twitch-auth-php#1]
Hey there! Learning Twitch Auth and all and was testing this example but noticed that main.js is empty?

Thanks!

**Comment by thehamsti** [comment]
Hi i realize you closed this already so you probably have already figured it out but this was a very basic shell of an authentication example. Javascript is not necessary in this example. I should remove the main.js file though that is my fault.

**Comment by LogicalSoIutions** [comment]
Yea I did figure it out same day, meant to close it then. Realized that after I posted it, just was dead tired lol
